version: "3.8"

services:
  postgres:
    image: postgres:${POSTGRES_VERSION:-16.1-alpine}
    env_file: ./.env
    environment:
      - POSTGRES_LOGGING=true
    ports:
      - 127.0.0.1:${POSTGRES_PORT:-5432}:5432
    shm_size: '2gb'
    volumes:
      - ./config/postgresql/postgresql.conf:/etc/postgresql.conf
      - postgres-data:/var/lib/postgresql/data
    command: [
      "-c", "config_file=/etc/postgresql.conf"
    ]
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  nftcdn-extractor:
    build:
      context: .
      target: nftcdn-extractor
    env_file: ./.env
    volumes:
      - cache:/home/node/app/cache
    environment:
      - NETWORK=${NETWORK:-mainnet}
      - OGMIOS_HOST=${OGMIOS_HOST:-host.docker.internal}
      - OGMIOS_PORT=${OGMIOS_PORT:-1337}
    extra_hosts:
     - host.docker.internal:host-gateway
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  nftcdn-server:
    build:
      context: .
      target: nftcdn-server
    env_file: ./.env
    volumes:
      - cache:/home/node/app/cache
    environment:
      - NETWORK=${NETWORK:-mainnet}
      - KUBO_HOST=${KUBO_HOST:-host.docker.internal}
      - KUBO_PORT=${KUBO_PORT:-1882}
    ports:
      - 127.0.0.1:${NFTCDN_SERVER_PORT:-4700}:4700
    extra_hosts:
     - host.docker.internal:host-gateway
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

volumes:
  postgres-data:
  cache:
